esphome:
  name: vindriktning
  project:
    name: RuntimeError.VindriktningESPHome
    version: 1.0.0
  on_boot:
    priority: 800
    then: 
      - text_sensor.template.publish:
          id: led_color
          state: "Green"

esp8266:
    board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret vindriktning_apikey

ota:
  password: !secret vindriktning_otapassword

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning installation"
    password: "vindriktning"

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret vindriktning_username
    password: !secret vindriktning_password

uart:
  tx_pin: D0
  rx_pin: D2
  baud_rate: 9600

time:
  - platform: homeassistant
    id: time_utc
    timezone: "Etc/UTC"
    on_time_sync:
      - component.update: vindriktning_startup_time

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    disabled_by_default: true
  - platform: pm1006
    id: vindriktning_PM2_5
    pm_2_5:
      name: "PM 2.5 concentration"
      on_value_range:
      - below: 36
        then:
          - text_sensor.template.publish:
              id: led_color
              state: "Green"
      - above: 35
        below: 86
        then:
          - text_sensor.template.publish:
              id: led_color
              state: "Yellow"
      - above: 85
        then:
          - text_sensor.template.publish:
              id: led_color
              state: "Red"
  - platform: template
    id: vindriktning_startup_time
    name: "Startup time"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    disabled_by_default: true
    lambda: |-
      static float timestamp = (
        id(time_utc).utcnow().timestamp
      );
      return timestamp;

text_sensor:
  - platform: template
    id: led_color
    name: "LED color"
    update_interval: never
    disabled_by_default: true
  - platform: version
    name: "Version"
    disabled_by_default: true

binary_sensor:
  - platform: status
    name: "Vindriktning Connection status"
    device_class: connectivity
    disabled_by_default: true

button:
  - platform: restart
    name: "Restart"
    disabled_by_default: true