esphome:
  name: vindriktning
  project:
    name: RuntimeError.VindriktningESPHome
    version: "${vindriktning_esphome_version}"

substitutions:
    vindriktning_esphome_version: "20211222"

esp8266:
    board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifissid
  password: !secret wifipassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vindriktning ESPHome"

captive_portal:

web_server:
  port: 80

uart:
  tx_pin: D0
  rx_pin: D2
  baud_rate: 9600

time:
  - platform: sntp
    id: time_utc
    timezone: "Etc/UTC"
    on_time_sync:
      - component.update: vindriktning_startup_time

sensor:
  - platform: wifi_signal
    id: vindriktning_wifi_signal
    name: "Vindriktning ESPHome WiFi Signal"
    update_interval: 60s
  - platform: pm1006
    id: vindriktning_PM2_5
    pm_2_5:
      name: "PM 2.5 concentration"
    update_interval: 20s
  - platform: template
    id: vindriktning_startup_time
    name: "Startup time"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_utc).utcnow().timestamp
      );
      return timestamp;

text_sensor:
  - platform: template
    id: vindriktning_version
    name: "Vindriktning Version"
    update_interval: 1d
    lambda: |-
      return {"${vindriktning_esphome_version}"};

button:
  - platform: restart
    name: "Vindriktning Restart"